1.1.0 updated fileicon for High Sierra

diff --git a/fileicon b/fileicon
--- a/fileicon
+++ b/fileicon
@@ -12,7 +12,7 @@
 
 kTHIS_NAME=${BASH_SOURCE##*/}
 kTHIS_HOMEPAGE='https://github.com/mklement0/fileicon'
-kTHIS_VERSION='v0.1.8' # NOTE: This assignment is automatically updated by `make version VER=<newVer>` - DO keep the 'v' prefix.
+kTHIS_VERSION='v0.2.2' # NOTE: This assignment is automatically updated by `make version VER=<newVer>` - DO keep the 'v' prefix.
 
 unset CDPATH  # To prevent unpredictable `cd` behavior.
 
@@ -85,7 +85,7 @@ printUsage() {
 case $1 in
   --version)
     # Output version number and exit, if requested.
-    ver="v0.2.0"; echo "$kTHIS_NAME $kTHIS_VERSION"$'\nFor license information and more, visit '"$kTHIS_HOMEPAGE"; exit 0
+    ver="v0.2.2"; echo "$kTHIS_NAME $kTHIS_VERSION"$'\nFor license information and more, visit '"$kTHIS_HOMEPAGE"; exit 0
     ;;
   -h|--help)
     # Print usage information and exit.
@@ -184,51 +184,39 @@ hasIconsResource() {
 #  setCustomIcon <fileOrFolder> <imgFile>
 setCustomIcon() {
 
-  local fileOrFolder=$1 imgFile=$2 byteStr tmpDir sourceFileWithResourceFork targetFileWithResourceFork
+  local fileOrFolder=$1 imgFile=$2
 
   [[ (-f $fileOrFolder || -d $fileOrFolder) && -r $fileOrFolder && -w $fileOrFolder ]] || return 3
   [[ -f $imgFile ]] || return 3
 
-  # Step 1: Create the icns resource by using `sips -i` on a temporary copy of the
-  #         image file, which puts the icns resource into the resource fork of that
-  #         temporary copy.
+  # !!
+  # !! Sadly, Apple decided to remove the `-i` / `--addicon` option from the `sips` utility.
+  # !! Therefore, use of *Cocoa* is required, which we do *via Python*, which has the added advantage
+  # !! of creating a *set* of icons from the source image, scaling as necessary to create a
+  # !! 512 x 512 top resolution icon (whereas sips -i created a single, 128 x 128 icon).
+  # !! Thanks, https://apple.stackexchange.com/a/161984/28668
+  # !!
+  # !! Note: setIcon_forFile_options_() seemingly always indicates True, even with invalid image files, so
+  # !!       we attempt no error handling in the Python code.
+  /usr/bin/python - "$imgFile" "$fileOrFolder" <<'EOF' || return
+import Cocoa
+import sys
+Cocoa.NSWorkspace.sharedWorkspace().setIcon_forFile_options_(Cocoa.NSImage.alloc().initWithContentsOfFile_(sys.argv[1].decode('utf-8')), sys.argv[2].decode('utf-8'), 0)
+EOF
 
-  # Create a temp. dir. and a temp. copy of the image file inside it.
-  tmpDir=$(/usr/bin/mktemp -d -t "$kTHIS_NAME") || return
-  sourceFileWithResourceFork=$tmpDir/${imgFile##*/}
-  cp "$imgFile" "$sourceFileWithResourceFork" || return
-  # Assign an icon representation of the image file to the image file itself.
-  # This creates the resource fork we'll copy.
-  sips -i "$sourceFileWithResourceFork" >/dev/null || return
 
-  # Make sure a resource fork with icons was actually created.
-  hasIconsResource "$sourceFileWithResourceFork" || { echo "Failed to create resource fork with icons. Typically, this means that the input file is not a (valid) image file: $sourceFileWithResourceFork" >&2; return 1; }
+  # Verify that a resource fork with icons was actually created.
+  # For *files*, the resource fork is embedded in the file itself.
+  # For *folders* a hidden file named $'Icon\r' is created *inside the folder*.
+  [[ -d $fileOrFolder ]] && fileWithResourceFork=${fileOrFolder}/$kFILENAME_FOLDERCUSTOMICON || fileWithResourceFork=$fileOrFolder
+  hasIconsResource "$fileWithResourceFork" || {
+    cat >&2 <<EOF
+Failed to create resource fork with icons. Typically, this means that the specified image file is not supported or corrupt: $imgFile
+Supported image formats: jpeg | tiff | png | gif | jp2 | pict | bmp | qtif| psd | sgi | tga
+EOF
+    return 1
 
-  # Step 2: Add the resource fork to the file itself (if target is a file) / to the special hidden file inside the folder (if target is a folder)
-
-  # Determine what file to copy the resource fork to.
-  if [[ -d $fileOrFolder ]]; then
-    # Create the special, hidden file inside the folder that will store the icon in its resource fork.
-    targetFileWithResourceFork=${fileOrFolder}/$kFILENAME_FOLDERCUSTOMICON
-    : > "$targetFileWithResourceFork" || return
-    # Assign the com.apple.FinderInfo extended attribute with values that identify the file as
-    # both hidden from Finder and as a custom-icon file for the enclosing folder.
-    xattr -wx com.apple.FinderInfo "$kFI_BYTES_CUSTOMICONFILEFORFOLDER" "$targetFileWithResourceFork" || return
-  else
-    targetFileWithResourceFork=$fileOrFolder
-  fi
-
-  # Copy the resource fork to the target file.
-  cp "$sourceFileWithResourceFork/..namedfork/rsrc" "$targetFileWithResourceFork/..namedfork/rsrc" || { rm -rf "$tmpDir"; return 1; } && rm -rf "$tmpDir"
-
-  # Step 3: Turn on the custom-icon flag in the com.apple.FinderInfo extended attribute for the target file/folder itself.
-  if hasAttrib "$fileOrFolder" com.apple.FinderInfo; then
-    byteStr=$(getAttribByteString "$fileOrFolder" com.apple.FinderInfo) || return
-  else
-    byteStr=$kFI_BYTES_BLANK
-  fi
-  byteStr=$(printf %s "$byteStr" | patchByteInByteString $kFI_BYTEOFFSET_CUSTOMICON '|'$kFI_VAL_CUSTOMICON) || return
-  xattr -wx com.apple.FinderInfo "$byteStr" "$fileOrFolder" || return
+  }
 
   return 0
 }
@@ -399,9 +387,10 @@ done
 # --- End: OPTIONS PARSING: "$@" now contains all operands (non-option arguments).
 
 # Validate the command
-cmd=$1
+cmd=$(printf %s "$1" | tr '[:upper:]' '[:lower:]') # translate to all-lowercase - we don't want the command name to be case-sensitive
+[[ $cmd == 'remove' ]] && cmd='rm'  # support alias 'remove' for 'rm'
 case $cmd in
-  set|get|rm|test)
+  set|get|rm|remove|test)
     shift
     ;;
   *)
@@ -423,10 +412,13 @@ targetFileOrFolder=$1 imgFile= outFile=
 valid=0
 case $cmd in
   'set')
-    (( $# == 2 )) && {
+    (( $# <= 2 )) && {
       valid=1
-      imgFile=$2
-      [[ -f $imgFile && -r $imgFile ]] || die "Image file not found or not a (readable) file: $imgFile"
+      # If no image file was specified, the target file is assumed to be an image file itself whose image should be self-assigned as an icon.
+      (( $# == 2 )) && imgFile=$2 || imgFile=$1
+      # !! Apparently, a regular file is required - a process subsitution such
+      # !! as `<(base64 -D <encoded-file.txt)` is NOT supported by NSImage.initWithContentsOfFile()
+      [[ -f $imgFile && -r $imgFile ]] || die "Image file not found or not a (readable) regular file: $imgFile"
     }
     ;;
   'rm'|'test')
@@ -527,101 +519,68 @@ exit 0
 ####
 : <<'EOF_MAN_PAGE'
 # fileicon(1) - manage file and folder custom icons
-
 ## SYNOPSIS
-
-Manage custom icons for files and folders on OS X.
-
+Manage custom icons for files and folders on macOS.
 SET a custom icon for a file or folder:
-
-    fileicon set      <fileOrFolder> <imageFile>
-
+    fileicon set      <fileOrFolder> [<imageFile>]
 REMOVE a custom icon from a file or folder:
-
     fileicon rm       <fileOrFolder>
-
 GET a file or folder's custom icon:
-
     fileicon get [-f] <fileOrFolder> [<iconOutputFile>]
-
     -f ... force replacement of existing output file
-
 TEST if a file or folder has a custom icon:
-
     fileicon test     <fileOrFolder>
-
 All forms: option -q silences status output.
-
 Standard options: `--help`, `--man`, `--version`, `--home`
-
 ## DESCRIPTION
-
-`<fileOrFolder>` is the file or folder whose custom icon should be managed.  
-Note that symlinks are followed to their (ultimate target); that is, you  
-can only assign custom icons to regular files and folders, not to symlinks  
+`<fileOrFolder>` is the file or folder whose custom icon should be managed.
+Note that symlinks are followed to their (ultimate target); that is, you
+can only assign custom icons to regular files and folders, not to symlinks
 to them.
-
-`<imageFile>` can be an image file of any format supported by the system.  
+`<imageFile>` can be an image file of any format supported by the system.
 It is converted to an icon and assigned to `<fileOrFolder>`.
-
-`<iconOutputFile>` specifies the file to extract the custom icon to:  
-Defaults to the filename of `<fileOrFolder>` with extension `.icns` appended.  
-If a value is specified, extension `.icns` is appended, unless already present.  
-Either way, extraction fails if the target file already exists; use `-f` to  
-override.  
-Specify `-` to extract to stdout.  
-
-Command `test` signals with its exit code whether a custom icon is set (0)  
+If you omit `<imageFile>`, `<fileOrFolder>` must itself be an image file whose
+image should become its own icon.
+`<iconOutputFile>` specifies the file to extract the custom icon to:
+Defaults to the filename of `<fileOrFolder>` with extension `.icns` appended.
+If a value is specified, extension `.icns` is appended, unless already present.
+Either way, extraction fails if the target file already exists; use `-f` to
+override.
+Specify `-` to extract to stdout.
+Command `test` signals with its exit code whether a custom icon is set (0)
 or not (1); any other exit code signals an unexpected error.
-
 **Options**:
-
-  * `-f`, `--force`  
-    When getting (extracting) a custom icon, forces replacement of the  
+  * `-f`, `--force`
+    When getting (extracting) a custom icon, forces replacement of the
     output file, if it already exists.
-
-  * `-q`, `--quiet`  
-    Suppresses output of the status information that is by default output to  
+  * `-q`, `--quiet`
+    Suppresses output of the status information that is by default output to
     stdout.  
     Note that errors and warnings are still printed to stderr.
-
 ## NOTES
-
-Custom icons are stored in extended attributes of the HFS+ filesystem.  
-Thus, if you copy files or folders to a different filesystem that doesn't  
-support such attributes, custom icons are lost; for instance, custom icons  
+Custom icons are stored in extended attributes of the HFS+ filesystem.
+Thus, if you copy files or folders to a different filesystem that doesn't
+support such attributes, custom icons are lost; for instance, custom icons
 cannot be stored in a Git repository.
-
-To determine if a give file or folder has extended attributes, use  
+To determine if a give file or folder has extended attributes, use
 `ls -l@ <fileOrFolder>`.
-
-When setting a custom icon, the source image is resized to 128 x 128 pixels  
-and stored as a single icon, which the system resizes dynamically, depending  
-on context.  
-Currently, even if the source image file is itself an `.icns` file that  
-contains multiple icons with distinct resolutions, only the 128 x 128 icon  
-is assigned.
-
+When setting an image as a custom icon, a set of icons with several resolutions
+is created, with the highest resolution at 512 x 512 pixels.
+All icons created are square, so images with a non-square aspect ratio will
+appear distorted; for best results, use square imges.
 ## STANDARD OPTIONS
-
 All standard options provide information only.
-
-* `-h, --help`  
+* `-h, --help`
   Prints the contents of the synopsis chapter to stdout for quick reference.
-
-* `--man`  
-  Displays this manual page, which is a helpful alternative to using `man`, 
+* `--man`
+  Displays this manual page, which is a helpful alternative to using `man`,
   if the manual page isn't installed.
-
-* `--version`  
+* `--version`
   Prints version information.
-  
-* `--home`  
+
+* `--home`
   Opens this utility's home page in the system's default web browser.
-
 ## LICENSE
-
-For license information and more, visit the home page by running  
+For license information and more, visit the home page by running
 `fileicon --home`
-
 EOF_MAN_PAGE
